// This runner is auto-generated by Brittle

runTests()

async function runTests () {
  const test = (await import('brittle')).default

  test.pause()

  await import('./socket.js')
  await import('./stream-framed.js')
  await import('./stream-parallel.js')
  await import('./stream.js')
  await import('./udx.js')

  test.resume()
}
